#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_login:
    path: /user/login
    controller: App\Controller\UserController::login

app_inscription:
    path: /user/inscription
    controller: App\Controller\UserController::inscription

app_logout:
    path: /user/logout
    controller: App\Controller\UserController::logout

app_update_user:
    path: /user/update
    controller: App\Controller\UserController::update

app_delete_user:
    path: /user/delete
    controller: App\Controller\UserController::delete

app_profil:
    path: /user/profil
    controller: App\Controller\UserController::profil

app_upload:
    path: /file/upload
    controller: App\Controller\FileController::upload

app_show:
    path: /file/show
    controller: App\Controller\FileController::show

app_file_update:
    path: /file/update/{id}
    controller: App\Controller\FileController::update

app_file_delete:
    path: /file/delete/{id}
    controller: App\Controller\FileController::delete

app_home:
    path: /home
    controller: App\Controller\HomeController::home


